### PR TITLE
chore: regenerate openapi3 definitions

### PR DESCRIPTION
**Pull request by kleyow**

### CODE REVIEW

**Comment by mdebarros** [comment]
@elnyry-sam-k @kleyow seems that we have an old PR open to fix this issue --> https://github.com/mojaloop/sdk-scheme-adapter/pull/204

I assume that we can close that [sdk-scheme-adapter/pull/204](https://github.com/mojaloop/sdk-scheme-adapter/pull/204) since this PR fixes the issue?

**Comment by lewisdaly** [comment]
@kleyow should we also add either a circleci check or precommit step that makes sure that the latest definition is being used?

**Comment by kleyow** [comment]
No, I don't want that. If I'm working on X feature that uses the current definition and checks want me to update for a change in schema change Y, I have to now then make sure all Y's features are updated breaking scope of the PR.

Ideally I want it to be a focused update where updating the schema and code is isolated from any features/fix/other prs.

**Comment by lewisdaly** [comment]
Yep, I can certainly agree with that rationale.

**Review by lewisdaly — APPROVED** [review]

**Comment by kleyow** [comment]
I believe so @mdebarros . I'll let have Sam have the final say in closing #204.

**Comment by elnyry-sam-k** [comment]
Thanks @kleyow , @mdebarros , closed #204

**Pull request merged**
