### PR TITLE
chore(package): latest sdk-standard-components

### PR DESCRIPTION
**Pull request by eoln**

### CODE REVIEW

**Comment by lewisdaly** [comment]
Hmm I wonder what broke

**Comment by sridharvoruganti** [comment]
Test suite failed to run:
Cannot find module './lib/mojaloop-requests' from 'node_modules/@mojaloop/sdk-standard-components/index.js'

I think 'mojaloop-requests' directory renamed to 'requests', so it should be now,  const { MojaloopRequests, ThirdpartyRequests } = require('./lib/requests');

**Comment by lewisdaly** [comment]
Damn, I thought I had made the exports backwards compatible.

**Comment by eoln** [comment]
I prepared the fix https://github.com/mojaloop/sdk-standard-components/pull/72

**Pull request merged**
